### ISSUE TITLE
A question of quad_dynamic_simple position step.

### ISSUE THREAD

**Issue by HenryHuYu** [lis-epfl/apg_trajectory_tracking#4]
Hi, Great work you've done! When I read the code in quad_dynamic_simple.py, I found
`px_new = px + 0.5 * dt * dt * acc_x + 0.5 * dt * vx
py_new = py + 0.5 * dt * dt * acc_y + 0.5 * dt * vy
pz_new = pz + 0.5 * dt * dt * acc_z + 0.5 * dt * vz`

I am really confused about the 0.5 before dt * v? could you plz give a hint about it?

also could you plz explain what is a "torch_kinv_ang_vel_tau" varieble? Thank you very much

**Comment by NinaWie** [comment]
Hi, thanks for your interest and very sorry for the late reply! 
As said in our paper, our environment is based on the Python implementation of a gym environment for quadrotors available [here](https://github.com/ngc92/quadgym). We use the integration from that implementation, see [here](https://github.com/ngc92/quadgym/blob/f7eb2fecaad5fcfbf2b8a5b9ef3062b809b64b99/gym_quadrotor/dynamics/dynamics.py#L96). 
Then, we made the quadrotor model more complex and aligned it with the model implemented in the flightmare simulator. In Flightmare, the "kinv_ang_vel_tau" is defined [here](https://github.com/uzh-rpg/flightmare/blob/d4218aedac18cbe9364a0a0df10ab992c4b65e4f/flightlib/include/flightlib/objects/quadrotor.hpp#L91) and is used as a constant in computing the body torque. 
I'm closing this for now, feel free to reopen.
