### ISSUE TITLE
matplotlib 3d not working

### ISSUE THREAD

**Issue by vwueest** [lis-epfl/apg_trajectory_tracking#6]
For me the matplotlib 3d stopped working 
using Ubuntu 20.04, python 3.8.16, matplotlib 3.7.4
@NinaWie could you 
1. check your version of matplotlib
2. and also if changing this works for you as well:
`rendering.py`, line 400:
```python
    ax = plt.axes(projection="3d")
    # ax = axes3d.Axes3D(fig)
```
If so, i'd say we change the code to that since that fixed the rendering for me

**Comment by NinaWie** [comment]
Thanks for checking this. My version of matplotlib was 3.3, so quite old. The rendering worked in 3.3 with both lines (either `ax = axes3d.Axes3D(fig)` or `ax = plt.axes(projection="3d")`. When I updated matplotlib, only the new version (`ax = plt.axes(projection="3d")`), worked, as you observed. I therefore agree to changing the line :)

**Comment by vwueest** [comment]
Alright, done, updated
https://github.com/lis-epfl/apg_trajectory_tracking/commit/45c7521f3ddd605c3e87b481fea9547e1cad9925
